
# SpeedrEye - KITTI Viandantes
# Clases: ['Pedestrian', 'Cyclist']

path: /run/media/aerok/XtraDisk/Documentos/Academic/SAMIA/SpeedrEye/notebooks/data/kitti_filtered
train: images/train
val: images/val
test: images/test

names:
  0: Pedestrian
  1: Cyclist

nc: 2
